version: '3.4'
services:
  drupal:
    image: drupal:latest
    container_name: drupal
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
    ports:
      - 8080:80
    links:
      - database

  database:
    container_name: drupal-db
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: generic
      POSTGRES_USER: nobody
      POSTGRES_DB: drupal
