version: '3.4'
services:
  drupal:
    build:
      context: ./app
    container_name: drupal-volume
    volumes:
      - drupal:/var/www/html

  server:
    image: wizdevops/drupal:8-alpine
    container_name: drupal-server
    volumes:
      - drupal:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - db
      - drupal
    links:
      - db

  db:
    container_name: drupal-db
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: generic
      POSTGRES_USER: nobody
      POSTGRES_DB: drupal

volumes:
  drupal:
    driver: local-persist
    driver_opts:
      mountpoint: /home/dminca/Repos/open-source/others/drupal-docker/www
